# repos:
#   - hooks:
#       - id: trailing-whitespace
#         args: ["--verbose"]
#       - id: end-of-file-fixer
#         args: ["--verbose"]
#       - id: check-added-large-files
#         args: ["--verbose"]
#       - id: check-yaml
#         args: ["--verbose"]

#         #  - args:
#         #    - --branch
#         #    - master
#         #    id: no-commit-to-branch
#     repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v3.4.0

#   - hooks:
#       - id: snakefmt
#         args: ["--verbose"]

#     repo: https://github.com/snakemake/snakefmt
#     rev: 0.4.0

#   - hooks:
#       - id: commitizen
#         args: ["--verbose"]
#         stages:
#           - commit-msg
#     repo: https://github.com/commitizen-tools/commitizen
#     rev: v2.17.12
