name: ashleys-qc-pipeline advanced workflow checks

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

jobs:
  Testing-with-MultiQC:
    runs-on: ubuntu-latest
    needs:
      - Formatting
      - Linting
      - Testing-basic
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Add Conda to system path
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: conda install -c conda-forge mamba

      - name: Setup Snakemake
        run: mamba install -c conda-forge -c bioconda snakemake==7.32.4

      - name: List options of workflow
        run: |
          snakemake --cores 1 --config list_commands=True --verbose --debug

      - name: Run workflow
        run: |
          snakemake --cores 1 --use-conda --configfile .tests/config/simple_config_ashleys.yaml --config MultiQC=True \
          --conda-frontend mamba -p --verbose --debug --snakefile workflow/Snakefile

  Testing-with-ms-norm:
    runs-on: ubuntu-latest
    needs:
      - Formatting
      - Linting
      - Testing-basic
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Add Conda to system path
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: conda install -c conda-forge mamba

      - name: Setup Snakemake
        run: mamba install -c conda-forge -c bioconda snakemake==7.32.4

      - name: List options of workflow
        run: |
          snakemake --cores 1 --config list_commands=True --verbose --debug

      - name: Run workflow
        run: |
          snakemake --cores 1 --use-conda --configfile .tests/config/simple_config_ashleys.yaml --config multistep_normalisation=True \
          --conda-frontend mamba -p --verbose --debug --snakefile workflow/Snakefile

  Testing-with-hg38:
    runs-on: ubuntu-latest
    needs:
      - Formatting
      - Linting
      - Testing-basic
    # - Testing-basic-with-slurm
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Add Conda to system path
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: conda install -c conda-forge mamba

      - name: Setup Snakemake
        run: mamba install -c conda-forge -c bioconda snakemake==7.32.4

      - name: List options of workflow
        run: |
          snakemake --cores 1 --config list_commands=True --verbose --debug

      - name: Run workflow
        run: |
          snakemake --cores 1 --use-conda --config reference=hg38 use_light_data=True chromosomes=[chr17] \
          --conda-frontend mamba -p --verbose --debug --snakefile workflow/Snakefile

  Testing-with-hg19:
    runs-on: ubuntu-latest
    needs:
      - Formatting
      - Linting
      - Testing-basic
    # - Testing-basic-with-slurm
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Add Conda to system path
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: conda install -c conda-forge mamba

      - name: Setup Snakemake
        run: mamba install -c conda-forge -c bioconda snakemake==7.32.4

      - name: List options of workflow
        run: |
          snakemake --cores 1 --config list_commands=True --verbose --debug

      - name: Run workflow
        run: |
          snakemake --cores 1 --use-conda --config reference=hg19 use_light_data=True chromosomes=[chr17] \
          --conda-frontend mamba -p --verbose --debug --snakefile workflow/Snakefile

  Testing-with-T2T:
    runs-on: ubuntu-latest
    needs:
      - Formatting
      - Linting
      - Testing-basic
    # - Testing-basic-with-slurm
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Add Conda to system path
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: conda install -c conda-forge mamba

      - name: Setup Snakemake
        run: mamba install -c conda-forge -c bioconda snakemake==7.32.4

      - name: List options of workflow
        run: |
          snakemake --cores 1 --config list_commands=True --verbose --debug

      - name: Run workflow
        run: |
          snakemake --cores 1 --use-conda --config reference=T2T use_light_data=True chromosomes=[chr17] \
          --conda-frontend mamba -p --verbose --debug --snakefile workflow/Snakefile

  Testing-with-mm10:
    runs-on: ubuntu-latest
    needs:
      - Formatting
      - Linting
      - Testing-basic
    # - Testing-basic-with-slurm
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Add Conda to system path
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: conda install -c conda-forge mamba

      - name: Setup Snakemake
        run: mamba install -c conda-forge -c bioconda snakemake==7.32.4

      - name: List options of workflow
        run: |
          snakemake --cores 1 --config list_commands=True --verbose --debug

      - name: Run workflow
        run: |
          snakemake --cores 1 --use-conda --config reference=T2T use_light_data=True chromosomes=[chr17] \
          --conda-frontend mamba -p --verbose --debug --snakefile workflow/Snakefile

  # Testing_publishdir:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4.1.7
  #     - name: Testing data
  #       uses: snakemake/snakemake-github-action@v1.24.0
  #       with:
  #         directory: .
  #         snakefile: ./workflow/Snakefile
  #         stagein: "conda config --set channel_priority flexible"
  #         args: "--cores 1 --use-conda --configfile .tests/config/simple_config_ashleys.yaml --config publishdir=.tests/data_chr17_publishdir --conda-frontend mamba -p --verbose --debug"
  #     - name: Testing report
  #       uses: snakemake/snakemake-github-action@v1.24.0
  #       with:
  #         directory: .
  #         snakefile: ./workflow/Snakefile
  #         args: "--cores 1 --use-conda --configfile .tests/config/simple_config_ashleys.yaml --config publishdir=.tests/data_chr17_publishdir --conda-frontend mamba --report report.zip"
